services:
  news-db:
    image: postgres
    environment:
      POSTGRES_DB: news
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
    volumes:
      - news-db:/data/postgres
    ports:
      - "5433:5432"

volumes:
  news-db: