server:
  port: 8081
spring:
  kafka:
    bootstrap-servers: "localhost:9092"
    streams:
      bootstrap-servers: "localhost:9092"
    producer:
      bootstrap-servers: "localhost:9092"
  datasource:
    url: jdbc:postgresql://127.0.0.1:5433/news
    username: admin
    password: admin
  liquibase:
    change-log: db/changelog.xml

